package exception;

import java.util.Scanner;

public class FinallyRunner {

	public static void main(String[] args) {
		Scanner sc = null;
		try {
			sc = new Scanner(System.in);
			int[] numbers = { 12, 3, 4, 5 };
			int number = numbers[2];

		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			System.out.println("Before Scanner Close");
			sc.close();
		}

		System.out.println("Just before closing out main");

	}

}
